import { ComponentData } from './types'

export function generateSmartPrompt(component: ComponentData): string {
  return `# ${component.name} - Smart Prompt

## Component Description
${component.description}

## Dependencies
Install the following packages:
\`\`\`bash
npm install ${component.dependencies.join(' ')}
\`\`\`

## Full Component Code
\`\`\`tsx
${component.code}
\`\`\`

## Integration Instructions
${component.integration}

## Customization Guide
You can customize this component by:
1. Adjusting the color scheme in the className properties
2. Modifying animation durations in the transition properties
3. Changing sizes using Tailwind CSS utilities
4. Adding your own interactive handlers

## AI Adaptation Prompt
Use this prompt with your AI assistant to adapt this component:

"I have a ${component.name} component. I need you to adapt it to match my project's design system. Here are my requirements:
- Color scheme: [YOUR_COLORS]
- Animation speed: [YOUR_PREFERENCE]
- Size/spacing: [YOUR_SPECS]
- Additional features: [YOUR_NEEDS]

Please modify the component code while preserving the core functionality and smooth animations."

---
Generated by PropLib - AI-Native UI Platform
Tags: ${component.tags.join(', ')}
Category: ${component.category}
`
}

export function copyToClipboard(text: string): Promise<void> {
  if (navigator.clipboard && navigator.clipboard.writeText) {
    return navigator.clipboard.writeText(text)
  }

  const textArea = document.createElement('textarea')
  textArea.value = text
  textArea.style.position = 'fixed'
  textArea.style.left = '-999999px'
  document.body.appendChild(textArea)
  textArea.select()

  try {
    document.execCommand('copy')
    return Promise.resolve()
  } catch (err) {
    return Promise.reject(err)
  } finally {
    document.body.removeChild(textArea)
  }
}
