import { createClient } from '@supabase/supabase-js'

// Supabase client for client-side operations (uses anon key)
export const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL || '',
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ''
)

// Supabase client for server-side admin operations (uses service role key)
export const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL || '',
  process.env.SUPABASE_SERVICE_ROLE_KEY || ''
)

// Database types (will be auto-generated by Supabase in production)
export interface ComponentRow {
  id: string
  name: string
  description: string
  category: 'headers' | 'search' | 'navigation' | 'cards' | 'forms' | 'animations'
  tags: string[]
  code: string
  dependencies: string[]
  integration: string
  smart_prompt: string | null
  preview_component_path: string
  created_at: string
  updated_at: string
  view_count: number
  copy_count: number
}

export interface AnalyticsEvent {
  id: number
  component_id: string
  event_type: 'view' | 'copy' | 'search'
  event_data: Record<string, any> | null
  created_at: string
}

export interface SearchQuery {
  id: number
  query: string
  results_count: number
  created_at: string
}

export interface PopularComponent {
  id: string
  name: string
  category: string
  view_count: number
  copy_count: number
  popularity_score: number
}
